active_theme: default
address: South Africa
author: Heritage Road Map Team
baseurl: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
description: Researching and documenting South African indigenous plants through  scientific
  study and botanical research.
email: info@heritagemap.org
facebook_username: your_facebook
github_username: MrViincciLeRoy
google_analytics: UA-XXXXXXXXX-X
instagram_username: your_instagram
linkedin_username: your_linkedin
markdown: kramdown
paginate: 10
paginate_path: /posts/page:num/
theme_colors:
  background: '#faf5ff'
  footer_bg: '#f5f3ff'
  footer_text: '#6d28d9'
  link: '#8b5cf6'
  link_hover: '#7c3aed'
  navbar_bg: '#ffffff'
  navbar_text: '#5b21b6'
  primary: '#8b5cf6'
  secondary: '#a78bfa'
  text: '#4c1d95'
theme_settings:
  font_family_base: Lora
  font_family_headings: Open Sans
  masthead_overlay: 0.5
title: Heritage Road Map Foundation
twitter_username: your_twitter
url: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
