active_theme: default
address: South Africa
author: Heritage Road Map Team
baseurl: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
description: Researching and documenting South African indigenous plants through  scientific
  study and botanical research.
email: Viincci@proton.me
facebook_username: your_facebook
github_username: MrViincciLeRoy
google_analytics: UA-XXXXXXXXX-X
instagram_username: your_instagram
linkedin_username: your_linkedin
phone: ''
title: Memoir of Viincci
twitter_username: your_twitter
url: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
