active_theme: default
address: South Africa
author: Heritage Road Map Team
baseurl: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
description: Researching and documenting South African indigenous plants through  scientific
  study and botanical research.
email: info@heritagemap.org
facebook_username: your_facebook
github_username: MrViincciLeRoy
google_analytics: UA-XXXXXXXXX-X
instagram_username: your_instagram
linkedin_username: your_linkedin
markdown: kramdown
paginate: 10
paginate_path: /posts/page:num/
theme_colors:
  background: '#000000'
  footer_bg: '#e0f2fe'
  footer_text: '#0369a1'
  link: '#000000'
  link_hover: '#0284c7'
  navbar_bg: '#ffffff'
  navbar_text: '#075985'
  primary: '#000000'
  secondary: '#000000'
  text: '#000000'
theme_settings:
  font_family_base: Lora
  font_family_headings: Open Sans
  masthead_overlay: 0.5
title: Heritage Road Map Foundation
twitter_username: your_twitter
url: https://mrviinccileroy.github.io/startbootstrap-clean-blog-jekyll/
